all:
	g++ -Wall -g \
		-o dpm dpm.cc
	gcc -Wall -g \
		-o hello hello.c
	gcc -Wall -g \
		-o input input.c
	gcc -Wall -g \
		-o fibonacci fibonacci.c
	gcc -Wall -g \
		-o quicksort quicksort.c

clean:
	rm -f \
		dpm \
		hello \
		input \
		fibonacci \
		quicksort
