all:
	gcc -g -o ptype ptype.c
	gcc -g -o set set.c
	gcc -g -o set2 set2.c
	gcc -g -o save-restore save-restore.c
	gcc -g -o stack-backtrace stack-backtrace.c
	gcc -g -o stack stack.c
	gcc -g -o fib fib.c
	gcc -g -o prefix prefix.c

clean:
	rm -f ptype set set2 save-restore stack-backtrace stack fib prefix 
